baseURL = 'https://dissinmanga.github.io/'
locale = 'en-us'
title = '今天嘴漫畫'
theme = 'congo'

[params]
	enableSearch = true
	mainSections = ["post"]

[params.homepage]
	layout = "page"
	showRecent = true
	recentItemsNumber = 10
	showMoreLink = true
 	cardView = false

[[menu.main]]
	name = "貼文"
	url = "/post/" 
