baseURL = 'https://dissinmanga.github.io/'
locale = "zh-hant"
title = '今天嘴漫畫'
theme = 'congo'
defaultContentLanguage = "zh-hant"
disableLanguages = ["en"]

summaryLength = 0
hasCJKLanguage = true

[taxonomies]

[params]
	colorScheme = "cherry"
	enableSearch = true
	mainSections = ["post"]

[params.homepage]
	layout = "page"
	showRecent = true
	recentLimit = 6

[params.header]
	layout = "basic"

[params.footer]
	showAppearanceSwitcher = true

[params.article]
	invertPagination = true

[pagination]
	pagerSize = 30

[[menu.main]]
	name = "文章"
	url = "/post/" 

[[menu.main]]
	name = "隨機"
	url = "/#random" 

[privacy.youtube]
    disabled = false
    privacyEnhanced = true

[outputs]
	home = ["HTML", "RSS", "JSON"]
